### ISSUE TITLE
Cannot compile with latest 2025.2.2 ESPHome

### ISSUE THREAD

**Issue by Rudd-O** [limengdu/MR60BHA2_ESPHome_external_components#11]
With or without

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/limengdu/MR60BHA2_ESPHome_external_components
      ref: main
    components: [ seeed_mr60bha2 ]
    refresh: 0s
```

I get

```
src/esphome/components/seeed_mr60bha2/seeed_mr60bha2.cpp:132:13: error: 'class esphome::seeed_mr60bha2::MR60BHA2Component' has no member named 'has_target_binary_sensor_'
```

**Comment by Rudd-O** [comment]
Related: https://github.com/esphome/issues/issues/6108

Workaround:

```yaml
binary_sensor:
  - platform: seeed_mr60bha2
    has_target:
      name: "Presence Information"
````

**Comment by limengdu** [comment]
https://github.com/limengdu/MR60BHA2_ESPHome_external_components/blob/f875eba14198a61f13d39182ba6c2558b7401511/example/mr60bha2.yaml#L11

**Comment by Rudd-O** [comment]
awesome bro, when is this hitting upstream?  do we have a pr open?

**Comment by Rudd-O** [comment]
I tried your latest branch as external component and it didn't fix the issue AT ALL.  please reopen.
